### ISSUE TITLE
 ImportError: cannot import name 'ALL'

### ISSUE THREAD

**Issue by mymusise** [jsocol/django-ratelimit#116]
I got a error in version 1.0.1 like this 

    decorators.py", line 7, in <module>
        from ratelimit import ALL, UNSAFE
    ImportError: cannot import name 'ALL'

but it work in version 1.0.0

**Comment by adamchainz** [comment]
`ALL` is there in `__init__` still: https://github.com/jsocol/django-ratelimit/blob/master/ratelimit/__init__.py

Try reinstalling it? Are you using `pip`? What version of Python?

**Comment by mymusise** [comment]
@adamchainz  thanks for your quick answer,
I reinstall by using pip but not work yeah, I use Python3.5.2 as my environment.

I got the error when I call decorators like this

    from ratelimit.decorators import ratelimit

I think it wouldn't load `ratelimit.decorators.__init__` if I only import like this

**Comment by adamchainz** [comment]
Python imports the `__init__` file for any package before even touching the submodules, that's just how `import` works.

If you look at the changes from 1.0.0 to 1.0.1, you'll see nothing is really suspicious: https://github.com/jsocol/django-ratelimit/compare/v1.0.0...master

**Comment by mymusise** [comment]
Yes, you're right, thanks for your help and patience.

**Comment by adamchainz** [comment]
So it's working for you now?
