### ISSUE TITLE
Please update new version to PyPi

### ISSUE THREAD

**Issue by andrei-kondakov** [jsocol/django-ratelimit#186]
Please upload new stable version of django-ratelimit to PyPi.

2.0 isn't working with Django 2.1 due to:

`"ratelimit/utils.py", line 109, in is_ratelimited
    parts = (fn.__module__, fn.__name__)
AttributeError: 'functools.partial' object has no attribute '__module__'`

**Comment by ankond** [comment]
I fix my view
```
from django.views.generic import View
from ratelimit.decorators import ratelimit

class MyView(View):
     @method_decorator(ratelimit(key='ip', rate='1/m', method='GET'))
    def get(self, request):
        pass
```

to 

```
from django.views.generic import View
from ratelimit.decorators import ratelimit

class MyView(View):
    @ratelimit(key='ip', rate='1/m', method='GET')
    def get(self, request):
        pass
```

And its worked with django-ratelimit 2.0.0 (current PyPi version) and django 2.1.

**Comment by hartwork** [comment]
:+1: for a new release

**Comment by PabloCastellano** [comment]
Hi @jsocol, could you release a new version to pypi? There have been quite some changes since last release. Thanks a lot!

**Comment by si14** [comment]
It would be amazing to move this forward, especially with #198!

**Comment by AlonFasta** [comment]
Both Django2.2 support and 'ratelimit' decorator changes (that allows better support to class based views rate counter) are crucial for our use.
Any updates on next version release to PyPi?
Thanks! much appreciated 👏

**Comment by jsocol** [comment]
[v3.0.0](https://pypi.org/project/django-ratelimit/3.0.0/) is on PyPI! Thanks all for your patience and nudges
